import { useEffect, useMemo, useState, type DragEvent, type MouseEvent } from 'react';
import type { LearningQuestion, QuestionInteraction, QuestionType } from '@interactiq/contracts';

const uid = () => crypto.randomUUID();
const tokens = (template: string) => template.split(/(\[\[[\s\S]*?\]\])/g).filter(Boolean);
const markerAnswers = (template: string) => tokens(template).filter((part) => part.startsWith('[[')).map((part) => part.slice(2, -2).split('|').map((v) => v.trim()).filter(Boolean));

export const defaultInteraction = (type: QuestionType): QuestionInteraction | null => {
  if (type === 'FILL_IN_THE_BLANKS') return { kind: 'fill_blank', template: 'Saya suka [[minum]] kopi.', blanks: [{ id: uid(), answers: ['minum'], mode: 'text', options: [] }], ignoreAccents: false };
  if (type === 'DRAG_AND_DROP') return { kind: 'drag_drop', template: 'Tahun kemerdekaan Malaysia ialah [[1957]].', blanks: [{ id: uid(), answer: '1957' }], distractors: ['1963', '1987'] };
  if (type === 'MATH_RESPONSE') return { kind: 'math_response', calculator: true };
  if (type === 'LABELLING') return { kind: 'labelling', imageUrl: '', labels: [], distractors: [] };
  if (type === 'HOTSPOT') return { kind: 'hotspot', imageUrl: '', shape: 'rectangle', regions: [] };
  if (type === 'REORDER') return { kind: 'reorder', items: ['Langkah pertama', 'Langkah kedua', 'Langkah ketiga'] };
  if (type === 'CATEGORIZE') return { kind: 'categorize', categories: [
    { id: uid(), name: 'Category 1', items: [{ id: uid(), text: 'Answer 1' }] },
    { id: uid(), name: 'Category 2', items: [{ id: uid(), text: 'Answer 2' }] },
  ], partialCredit: true };
  if (type === 'MATCH') return { kind: 'match', pairs: [{ id: uid(), prompt: 'Prompt 1', response: 'Match 1' }, { id: uid(), prompt: 'Prompt 2', response: 'Match 2' }], partialCredit: true };
  if (type === 'MATCH_TABLE_GRID') { const columnA=uid(), columnB=uid(), rowA=uid(), rowB=uid(); return { kind: 'match_table_grid', rows: [{ id: rowA, text: 'Row 1' }, { id: rowB, text: 'Row 2' }], columns: [{ id: columnA, text: 'Column 1' }, { id: columnB, text: 'Column 2' }], correctCells: [`${rowA}:${columnA}`, `${rowB}:${columnB}`], allowMultiplePerRow: false, partialCredit: true }; }
  return null;
};

function TemplatePreview({ template, values }: { template: string; values?: string[] }) {
  let blank = 0;
  return <div className="blank-preview">{tokens(template).map((part, index) => {
    if (!part.startsWith('[[')) return <span key={index}>{part}</span>;
    const current = values?.[blank] || part.slice(2, -2).split('|')[0] || 'Blank'; blank += 1;
    return <strong key={index}>{current}</strong>;
  })}</div>;
}

function StringListEditor({ addLabel, items, label, minimum = 0, onChange }: { addLabel: string; items: string[]; label: string; minimum?: number; onChange: (items: string[]) => void }) {
  return <div className="string-list-editor"><b>{label}</b>{items.map((item, index) => <div key={index} className="string-list-row"><span>{index + 1}</span><input value={item} onChange={(event) => onChange(items.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} /><button aria-label={`Delete ${label} ${index + 1}`} disabled={items.length <= minimum} onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))} type="button">×</button></div>)}<button className="add-interaction-item" onClick={() => onChange([...items, ''])} type="button">＋ {addLabel}</button></div>;
}

export function InteractionAuthoring({ interaction, onChange, onUploadImage, type }: { interaction: QuestionInteraction | null; onChange: (value: QuestionInteraction | null) => void; onUploadImage: (file: File) => Promise<string>; type: QuestionType }) {
  const current = interaction?.kind === defaultInteraction(type)?.kind ? interaction : defaultInteraction(type);
  useEffect(() => { if (current !== interaction) onChange(current); }, [type]);
  const upload = async (file?: File) => { if (!file || !current || !('imageUrl' in current)) return; onChange({ ...current, imageUrl: await onUploadImage(file) }); };
  if (!current) return null;

  if (current.kind === 'fill_blank' || current.kind === 'drag_drop') {
    const updateTemplate = (template: string) => {
      const found = markerAnswers(template);
      if (current.kind === 'fill_blank') onChange({ ...current, template, blanks: found.map((answers, i) => ({ id: current.blanks[i]?.id ?? uid(), answers, mode: current.blanks[i]?.mode ?? 'text', options: current.blanks[i]?.options ?? [] })) });
      else onChange({ ...current, template, blanks: found.map((answers, i) => ({ id: current.blanks[i]?.id ?? uid(), answer: answers[0] ?? '' })) });
    };
    return <section className="interaction-builder"><div className="interaction-tip"><b>Taip ayat dan jadikan jawapan sebagai ruang kosong</b><span>Gunakan dua kurungan siku, contoh: Saya suka <code>[[minum|minumkan]]</code> kopi.</span></div><textarea rows={4} value={current.template} onChange={(e) => updateTemplate(e.target.value)} /><TemplatePreview template={current.template} />
      {current.kind === 'fill_blank' ? <div className="blank-settings"><label className="switch-line"><input type="checkbox" checked={current.ignoreAccents} onChange={(e) => onChange({ ...current, ignoreAccents: e.target.checked })} /> Abaikan tanda aksen</label>{current.blanks.map((blank, index) => <article key={blank.id}><b>Blank {index + 1}</b><label>Jawapan diterima<input value={blank.answers.join(' | ')} onChange={(e) => onChange({ ...current, blanks: current.blanks.map((item, i) => i === index ? { ...item, answers: e.target.value.split('|').map((v) => v.trim()).filter(Boolean) } : item) })} /></label><label>Cara pelajar menjawab<select value={blank.mode} onChange={(e) => onChange({ ...current, blanks: current.blanks.map((item, i) => i === index ? { ...item, mode: e.target.value as 'text' | 'dropdown' } : item) })}><option value="text">Taip jawapan</option><option value="dropdown">Pilih dropdown</option></select></label>{blank.mode === 'dropdown' && <label>Pilihan tambahan<input placeholder="Asingkan dengan koma" value={blank.options.join(', ')} onChange={(e) => onChange({ ...current, blanks: current.blanks.map((item, i) => i === index ? { ...item, options: e.target.value.split(',').map((v) => v.trim()).filter(Boolean) } : item) })} /></label>}</article>)}</div> : <div className="blank-settings"><article><b>Bank jawapan</b><p className="muted">Jawapan betul datang daripada ruang [[...]]. Tambah atau buang pilihan salah secara berasingan.</p><StringListEditor addLabel="Add wrong choice" items={current.distractors} label="Wrong choices (optional)" onChange={(distractors) => onChange({ ...current, distractors })} /></article></div>}
    </section>;
  }

  if (current.kind === 'math_response') return <section className="interaction-builder math-author"><div><span className="math-icon">ƒ(x)</span><div><b>Math Response</b><p>Pelajar mendapat papan kekunci matematik dan kalkulator visual.</p></div></div><label className="switch-line"><input type="checkbox" checked={current.calculator} onChange={(e) => onChange({ ...current, calculator: e.target.checked })} /> Aktifkan kalkulator untuk pelajar</label></section>;

  if (current.kind === 'reorder') return <section className="interaction-builder"><div className="interaction-tip"><b>Rantaian jawapan yang betul</b><span>Tambah satu langkah dalam setiap kotak. Sistem akan mengacak susunan ini untuk pelajar.</span></div><StringListEditor addLabel="Add step" items={current.items} label="Correct order" minimum={2} onChange={(items) => onChange({ ...current, items })} /><div className="reorder-author-preview">{current.items.map((item, i) => <span key={`${item}-${i}`}><b>{i + 1}</b>{item || `Step ${i + 1}`}</span>)}</div></section>;

  if (current.kind === 'categorize') return <CategorizeAuthoring config={current} onChange={onChange} />;

  if (current.kind === 'match') return <MatchAuthoring config={current} onChange={onChange} />;
  if (current.kind === 'match_table_grid') return <MatchGridAuthoring config={current} onChange={onChange} />;

  if (current.kind === 'labelling') return <section className="interaction-builder"><ImageUpload imageUrl={current.imageUrl} onUpload={upload} /><p className="interaction-tip"><b>Klik pada gambar untuk menambah label</b><span>Setiap titik menjadi sasaran yang perlu dipadankan oleh pelajar.</span></p>{current.imageUrl && <div className="target-image" onClick={(e) => { const p = imagePoint(e); onChange({ ...current, labels: [...current.labels, { id: uid(), text: `Label ${current.labels.length + 1}`, ...p }] }); }}><img src={current.imageUrl} alt="Labelling canvas" />{current.labels.map((label, i) => <i key={label.id} style={{ left: `${label.x * 100}%`, top: `${label.y * 100}%` }}>{i + 1}</i>)}</div>}<div className="target-list">{current.labels.map((label, i) => <label key={label.id}><b>{i + 1}</b><input value={label.text} onChange={(e) => onChange({ ...current, labels: current.labels.map((item) => item.id === label.id ? { ...item, text: e.target.value } : item) })} /><button type="button" onClick={() => onChange({ ...current, labels: current.labels.filter((item) => item.id !== label.id) })}>×</button></label>)}</div><StringListEditor addLabel="Add wrong label" items={current.distractors} label="Wrong label choices (optional)" onChange={(distractors) => onChange({ ...current, distractors })} /></section>;

  return <section className="interaction-builder"><ImageUpload imageUrl={current.imageUrl} onUpload={upload} /><div className="hotspot-tools"><label>Bentuk hotspot<select value={current.shape} onChange={(e) => onChange({ ...current, shape: e.target.value as typeof current.shape })}><option value="point">Titik</option><option value="rectangle">Segi empat</option><option value="polygon">Poligon</option></select></label><span>{current.regions.length} kawasan betul</span></div><p className="interaction-tip"><b>Klik pada pusat jawapan yang betul</b><span>Saiz kawasan boleh dipilih sebagai titik, segi empat atau poligon.</span></p>{current.imageUrl && <div className="target-image hotspot-author" onClick={(e) => { const p = imagePoint(e); const d = current.shape === 'point' ? .035 : .085; const points = current.shape === 'polygon' ? [{ x: p.x, y: p.y-d }, { x:p.x+d,y:p.y+d }, { x:p.x-d,y:p.y+d }] : [{x:p.x-d,y:p.y-d},{x:p.x+d,y:p.y+d}]; onChange({ ...current, regions: [...current.regions, { id: uid(), points }] }); }}><img src={current.imageUrl} alt="Hotspot canvas" />{current.regions.map((region) => { const xs=region.points.map((p)=>p.x), ys=region.points.map((p)=>p.y); return <i className="hotspot-region" key={region.id} style={{ left:`${Math.min(...xs)*100}%`, top:`${Math.min(...ys)*100}%`, width:`${(Math.max(...xs)-Math.min(...xs))*100}%`, height:`${(Math.max(...ys)-Math.min(...ys))*100}%` }} onClick={(e) => { e.stopPropagation(); onChange({ ...current, regions: current.regions.filter((r) => r.id !== region.id) }); }}>✓</i>; })}</div>}</section>;
}

function ImageUpload({ imageUrl, onUpload }: { imageUrl: string; onUpload: (file?: File) => void }) { return <label className="image-upload-zone"><input accept="image/png,image/jpeg,image/webp" type="file" onChange={(e) => onUpload(e.target.files?.[0])} /><b>{imageUrl ? 'Tukar gambar' : '＋ Upload gambar'}</b><span>PNG, JPG atau WebP</span></label>; }
function imagePoint(event: MouseEvent<HTMLDivElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }; }

const seededShuffle = (items: string[], seed: string) => items.map((item, i) => ({ item, n: [...`${seed}${i}`].reduce((n,c)=>n+c.charCodeAt(0),0)%97 })).sort((a,b)=>a.n-b.n).map((x)=>x.item);

export function InteractiveStudentResponse({ question, value, onChange }: { question: LearningQuestion; value: string | string[] | undefined; onChange: (value: string | string[]) => void }) {
  const config = question.interaction;
  if (!config) return <textarea className="student-answer" rows={7} value={(value as string) ?? ''} onChange={(e) => onChange(e.target.value)} placeholder="Type your answer here…" />;
  if (config.kind === 'fill_blank') {
    const answers = Array.isArray(value) ? value : [];
    let blank = 0;
    return <div className="inline-question">{tokens(config.template).map((part, index) => { if (!part.startsWith('[[')) return <span key={index}>{part}</span>; const i=blank++; const item=config.blanks[i]; if (!item) return null; const choices=[...new Set([...item.answers,...item.options])].sort(); return item.mode === 'dropdown' ? <select key={index} value={answers[i] ?? ''} onChange={(e)=>onChange(replaceAt(answers,i,e.target.value))}><option value="">Pilih jawapan</option>{choices.map((choice)=><option key={choice}>{choice}</option>)}</select> : <input key={index} value={answers[i] ?? ''} onChange={(e)=>onChange(replaceAt(answers,i,e.target.value))} placeholder={`Blank ${i+1}`} />; })}</div>;
  }
  if (config.kind === 'drag_drop') return <DragBlankPlayer config={config} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  if (config.kind === 'math_response') return <MathPlayer calculator={config.calculator} value={Array.isArray(value) ? value.join('') : value ?? ''} onChange={onChange} />;
  if (config.kind === 'labelling') return <LabellingPlayer config={config} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  if (config.kind === 'hotspot') { let selected: {x:number;y:number}|null=null; try { selected=value && !Array.isArray(value) ? JSON.parse(value) : null; } catch {} return <div className="hotspot-player target-image" onClick={(e)=>onChange(JSON.stringify(imagePoint(e)))}><img src={config.imageUrl} alt="Choose the correct hotspot" />{selected && <i className="student-hotspot" style={{left:`${selected.x*100}%`,top:`${selected.y*100}%`}}>●</i>}</div>; }
  if (config.kind === 'reorder') return <ReorderPlayer items={config.items} seed={question.id} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  if (config.kind === 'categorize') return <CategorizePlayer config={config} seed={question.id} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  if (config.kind === 'match') return <MatchPlayer config={config} seed={question.id} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  if (config.kind === 'match_table_grid') return <MatchGridPlayer config={config} value={Array.isArray(value) ? value : []} onChange={onChange} />;
  return null;
}

function MatchAuthoring({ config, onChange }: { config: Extract<QuestionInteraction,{kind:'match'}>; onChange:(value:QuestionInteraction)=>void }) {
  const update=(id:string, field:'prompt'|'response', text:string)=>onChange({ ...config, pairs:config.pairs.map((pair)=>pair.id===id?{...pair,[field]:text}:pair) });
  return <section className="interaction-builder match-author"><div className="interaction-tip"><b>Build matching pairs</b><span>Each coloured column represents one correct prompt and response pair.</span></div><div className="match-pair-list">{config.pairs.map((pair,index)=><article key={pair.id}><span className={`pair-colour pair-colour-${index%6}`}>{index+1}</span><input aria-label={`Prompt ${index+1}`} value={pair.prompt} onChange={(e)=>update(pair.id,'prompt',e.target.value)} placeholder="Prompt"/><span>↔</span><input aria-label={`Response ${index+1}`} value={pair.response} onChange={(e)=>update(pair.id,'response',e.target.value)} placeholder="Matching response"/><button type="button" aria-label={`Remove pair ${index+1}`} disabled={config.pairs.length<=2} onClick={()=>onChange({...config,pairs:config.pairs.filter((item)=>item.id!==pair.id)})}>×</button></article>)}</div><button className="add-interaction-item" type="button" onClick={()=>onChange({...config,pairs:[...config.pairs,{id:uid(),prompt:`Prompt ${config.pairs.length+1}`,response:`Match ${config.pairs.length+1}`} ]})}>＋ Add pair</button><label className="switch-line"><input type="checkbox" checked={config.partialCredit} onChange={(e)=>onChange({...config,partialCredit:e.target.checked})}/> Allow partial grading</label></section>;
}

function CategorizeAuthoring({ config, onChange }: { config: Extract<QuestionInteraction,{kind:'categorize'}>; onChange:(value:QuestionInteraction)=>void }) {
  const updateCategory=(id:string, next:Partial<(typeof config.categories)[number]>)=>onChange({...config,categories:config.categories.map((category)=>category.id===id?{...category,...next}:category)});
  return <section className="interaction-builder categorize-author"><div className="interaction-tip"><b>Build categories and answer cards</b><span>Start with two categories. Add or remove categories and answers as needed.</span></div><div className="categorize-author-grid">{config.categories.map((category,index)=><article className={`category-colour-${index%6}`} key={category.id}><header><input aria-label={`Category ${index+1} name`} value={category.name} onChange={(event)=>updateCategory(category.id,{name:event.target.value})}/><button aria-label={`Delete category ${index+1}`} disabled={config.categories.length<=2} type="button" onClick={()=>onChange({...config,categories:config.categories.filter((item)=>item.id!==category.id)})}>×</button></header><div>{category.items.map((item,itemIndex)=><label key={item.id}><span>⠿</span><input aria-label={`Category ${index+1} answer ${itemIndex+1}`} value={item.text} onChange={(event)=>updateCategory(category.id,{items:category.items.map((answer)=>answer.id===item.id?{...answer,text:event.target.value}:answer)})}/><button aria-label={`Delete category ${index+1} answer ${itemIndex+1}`} disabled={category.items.length<=1} type="button" onClick={()=>updateCategory(category.id,{items:category.items.filter((answer)=>answer.id!==item.id)})}>×</button></label>)}</div><button className="add-interaction-item" type="button" onClick={()=>updateCategory(category.id,{items:[...category.items,{id:uid(),text:`Answer ${category.items.length+1}`} ]})}>＋ Add answer</button></article>)}</div><button className="add-interaction-item" disabled={config.categories.length>=8} type="button" onClick={()=>onChange({...config,categories:[...config.categories,{id:uid(),name:`Category ${config.categories.length+1}`,items:[{id:uid(),text:'New answer'}]}]})}>＋ Add category</button><label className="switch-line"><input type="checkbox" checked={config.partialCredit} onChange={(event)=>onChange({...config,partialCredit:event.target.checked})}/> Allow partial grading</label></section>;
}

function MatchGridAuthoring({ config, onChange }: { config: Extract<QuestionInteraction,{kind:'match_table_grid'}>; onChange:(value:QuestionInteraction)=>void }) {
  const cell=(row:string,column:string)=>`${row}:${column}`; const toggle=(row:string,column:string)=>{const key=cell(row,column); let correct=config.correctCells.includes(key)?config.correctCells.filter((item)=>item!==key):[...config.correctCells,key]; if(!config.allowMultiplePerRow&&correct.includes(key))correct=correct.filter((item)=>!item.startsWith(`${row}:`)||item===key); onChange({...config,correctCells:correct});};
  return <section className="interaction-builder match-grid-author"><div className="interaction-tip"><b>Build a match table</b><span>Edit row and column labels, then tick every correct cell.</span></div><div className="match-grid-scroll"><table><thead><tr><th>Prompts</th>{config.columns.map((column)=><th key={column.id}><input value={column.text} onChange={(e)=>onChange({...config,columns:config.columns.map((item)=>item.id===column.id?{...item,text:e.target.value}:item)})}/><button type="button" disabled={config.columns.length<=2} onClick={()=>onChange({...config,columns:config.columns.filter((item)=>item.id!==column.id),correctCells:config.correctCells.filter((key)=>!key.endsWith(`:${column.id}`))})}>×</button></th>)}<th><button type="button" onClick={()=>onChange({...config,columns:[...config.columns,{id:uid(),text:`Column ${config.columns.length+1}`}]})}>＋</button></th></tr></thead><tbody>{config.rows.map((row)=><tr key={row.id}><th><input value={row.text} onChange={(e)=>onChange({...config,rows:config.rows.map((item)=>item.id===row.id?{...item,text:e.target.value}:item)})}/></th>{config.columns.map((column)=><td key={column.id}><input type="checkbox" checked={config.correctCells.includes(cell(row.id,column.id))} onChange={()=>toggle(row.id,column.id)}/></td>)}<td><button type="button" disabled={config.rows.length<=2} onClick={()=>onChange({...config,rows:config.rows.filter((item)=>item.id!==row.id),correctCells:config.correctCells.filter((key)=>!key.startsWith(`${row.id}:`))})}>×</button></td></tr>)}</tbody></table></div><button className="add-interaction-item" type="button" onClick={()=>onChange({...config,rows:[...config.rows,{id:uid(),text:`Row ${config.rows.length+1}`}]})}>＋ Add row</button><div className="grid-switches"><label className="switch-line"><input type="checkbox" checked={config.allowMultiplePerRow} onChange={(e)=>onChange({...config,allowMultiplePerRow:e.target.checked})}/> Allow multiple selections per row</label><label className="switch-line"><input type="checkbox" checked={config.partialCredit} onChange={(e)=>onChange({...config,partialCredit:e.target.checked})}/> Allow partial grading</label></div></section>;
}

function MatchPlayer({ config, seed, value, onChange }: { config:Extract<QuestionInteraction,{kind:'match'}>;seed:string;value:string[];onChange:(value:string[])=>void }) { const choices=useMemo(()=>seededShuffle(config.pairs.map((pair)=>pair.id),seed),[seed,config.pairs.map((p)=>p.id).join('|')]); const [picked,setPicked]=useState(''); const assigned=new Map(value.map((item)=>item.split(':') as [string,string])); const assign=(left:string,right:string)=>{if(!right)return;onChange([...value.filter((item)=>!item.startsWith(`${left}:`)&&!item.endsWith(`:${right}`)),`${left}:${right}`]);setPicked('');}; return <div className="match-player"><div className="match-response-bank">{choices.map((id,index)=>{const pair=config.pairs.find((item)=>item.id===id)!;const used=value.some((item)=>item.endsWith(`:${id}`));return <button type="button" draggable disabled={used} className={`${picked===id?'picked ':''}pair-colour-${index%6}`} key={id} onClick={()=>setPicked(id)} onDragStart={(e)=>e.dataTransfer.setData('text/plain',id)}>{pair.response}</button>})}</div><div className="match-prompts">{config.pairs.map((pair,index)=>{const right=assigned.get(pair.id);const response=config.pairs.find((item)=>item.id===right)?.response;return <button type="button" key={pair.id} onClick={()=>assign(pair.id,picked)} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>assign(pair.id,e.dataTransfer.getData('text/plain'))}><span>{pair.prompt}</span><b className={response?`pair-colour-${index%6}`:''}>{response||'Choose a match'}</b></button>})}</div></div>; }

function CategorizePlayer({config,seed,value,onChange}:{config:Extract<QuestionInteraction,{kind:'categorize'}>;seed:string;value:string[];onChange:(value:string[])=>void}) {
  const [picked,setPicked]=useState(''); const items=useMemo(()=>seededShuffle(config.categories.flatMap((category)=>category.items.map((item)=>item.id)),seed),[seed,JSON.stringify(config.categories)]);
  const itemById=new Map(config.categories.flatMap((category)=>category.items).map((item)=>[item.id,item])); const assignment=new Map(value.map((entry)=>entry.split(':') as [string,string]));
  const assign=(itemId:string,categoryId:string)=>{if(!itemId)return;onChange([...value.filter((entry)=>!entry.startsWith(`${itemId}:`)),`${itemId}:${categoryId}`]);setPicked('');};
  const unassigned=items.filter((id)=>!assignment.has(id));
  return <div className="categorize-player"><aside><b>Answer bank</b><span>{unassigned.length} remaining</span><div>{unassigned.map((id)=><button className={picked===id?'picked':''} draggable key={id} type="button" onClick={()=>setPicked(id)} onDragStart={(event)=>event.dataTransfer.setData('text/plain',id)}>⠿ {itemById.get(id)?.text}</button>)}</div></aside><div className="categorize-player-grid">{config.categories.map((category,index)=><section className={`category-colour-${index%6}`} key={category.id} onClick={()=>assign(picked,category.id)} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>assign(event.dataTransfer.getData('text/plain'),category.id)}><h3>{category.name}</h3><div>{items.filter((id)=>assignment.get(id)===category.id).map((id)=><button draggable key={id} type="button" onDragStart={(event)=>event.dataTransfer.setData('text/plain',id)} onDoubleClick={()=>onChange(value.filter((entry)=>!entry.startsWith(`${id}:`)))}>⠿ {itemById.get(id)?.text}</button>)}</div><p>Drop answers here</p></section>)}</div></div>;
}

function MatchGridPlayer({ config, value, onChange }: {config:Extract<QuestionInteraction,{kind:'match_table_grid'}>;value:string[];onChange:(value:string[])=>void}) { const toggle=(row:string,column:string)=>{const key=`${row}:${column}`;if(value.includes(key))return onChange(value.filter((item)=>item!==key));const next=config.allowMultiplePerRow?value:value.filter((item)=>!item.startsWith(`${row}:`));onChange([...next,key]);};return <div className="student-match-grid match-grid-scroll"><table><thead><tr><th></th>{config.columns.map((column)=><th key={column.id}>{column.text}</th>)}</tr></thead><tbody>{config.rows.map((row)=><tr key={row.id}><th>{row.text}</th>{config.columns.map((column)=>{const key=`${row.id}:${column.id}`;return <td key={column.id}><label className={value.includes(key)?'checked':''}><input type="checkbox" checked={value.includes(key)} onChange={()=>toggle(row.id,column.id)}/><span>✓</span></label></td>})}</tr>)}</tbody></table></div>; }

const replaceAt = (values: string[], index: number, next: string) => { const result=[...values]; result[index]=next; return result; };

function DragBlankPlayer({ config, value, onChange }: { config: Extract<QuestionInteraction,{kind:'drag_drop'}>; value: string[]; onChange: (v:string[])=>void }) {
  const [picked,setPicked]=useState(''); const bank=useMemo(()=>seededShuffle([...config.blanks.map((b)=>b.answer),...config.distractors],config.template),[config.template]); let blank=0;
  const place=(i:number,text:string)=>{ if(!text)return; onChange(replaceAt(value,i,text)); setPicked(''); };
  return <div className="drag-player"><div className="inline-question">{tokens(config.template).map((part,index)=>{ if(!part.startsWith('[['))return <span key={index}>{part}</span>; const i=blank++; return <button className="drop-slot" key={index} onClick={()=>place(i,picked)} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>place(i,e.dataTransfer.getData('text/plain'))}>{value[i]||'Letak di sini'}</button>; })}</div><div className="answer-bank">{bank.map((item,i)=><button draggable key={`${item}-${i}`} className={picked===item?'picked':''} onClick={()=>setPicked(item)} onDragStart={(e)=>e.dataTransfer.setData('text/plain',item)}>{item}</button>)}</div></div>;
}

function MathPlayer({ calculator, value, onChange }: { calculator:boolean; value:string; onChange:(v:string)=>void }) { const keys=['7','8','9','÷','√','4','5','6','×','(', '1','2','3','−',')','0','.','π','+','=']; const append=(key:string)=>key==='='?undefined:onChange(value+(key==='−'?'-':key)); return <div className="math-player"><input aria-label="Mathematical answer" value={value} onChange={(e)=>onChange(e.target.value)} placeholder="Taip jawapan matematik" />{calculator&&<div className="math-keypad"><button type="button" onClick={()=>onChange(value.slice(0,-1))}>⌫</button><button type="button" onClick={()=>onChange('')}>Clear</button>{keys.map((key)=><button type="button" key={key} onClick={()=>append(key)}>{key}</button>)}</div>}</div>; }

function LabellingPlayer({ config, value, onChange }: { config: Extract<QuestionInteraction,{kind:'labelling'}>; value:string[]; onChange:(v:string[])=>void }) { const [picked,setPicked]=useState(''); const assigned=new Map(value.map((v)=>v.split(':') as [string,string])); const labels=seededShuffle([...config.labels.map((l)=>l.text),...config.distractors],config.imageUrl); const idFor=(text:string)=>config.labels.find((l)=>l.text===text)?.id ?? `wrong-${text}`; const place=(target:string,label:string)=>{if(!label)return; const next=value.filter((v)=>!v.endsWith(`:${target}`)&&!v.startsWith(`${label}:`)); onChange([...next,`${label}:${target}`]);setPicked('');}; return <div className="labelling-player"><div className="target-image"><img src={config.imageUrl} alt="Label this image" />{config.labels.map((target,i)=>{const placed=[...assigned].find(([,t])=>t===target.id)?.[0]; const text=config.labels.find((l)=>l.id===placed)?.text; return <button key={target.id} style={{left:`${target.x*100}%`,top:`${target.y*100}%`}} onClick={()=>place(target.id,idFor(picked))} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>place(target.id,e.dataTransfer.getData('text/plain'))}>{text||i+1}</button>;})}</div><div className="answer-bank">{labels.map((text,i)=><button draggable key={`${text}-${i}`} className={picked===text?'picked':''} onClick={()=>setPicked(text)} onDragStart={(e:DragEvent)=>e.dataTransfer.setData('text/plain',idFor(text))}>{text}</button>)}</div></div>; }

function ReorderPlayer({ items, seed, value, onChange }: {items:string[];seed:string;value:string[];onChange:(v:string[])=>void}) { const initial=useMemo(()=>{const shuffled=seededShuffle(items,seed);return items.length>1&&shuffled.every((item,index)=>item===items[index])?[...items.slice(1),items[0]!]:shuffled;},[items.join('|'),seed]); useEffect(()=>{if(!value.length)onChange(initial);},[seed]); const shown=value.length?value:initial; const move=(from:number,to:number)=>{const next=[...shown];const [item]=next.splice(from,1);if(item===undefined)return;next.splice(to,0,item);onChange(next);}; return <div className="reorder-player">{shown.map((item,i)=><article draggable key={`${item}-${i}`} onDragStart={(e)=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>move(Number(e.dataTransfer.getData('text/plain')),i)}><span>⠿</span><b>{i+1}</b><p>{item}</p><button disabled={i===0} onClick={()=>move(i,i-1)}>↑</button><button disabled={i===shown.length-1} onClick={()=>move(i,i+1)}>↓</button></article>)}</div>; }
